BaseURL = "http://piyushhbhutoria.github.io/"
languageCode = "en-us"
title = "Piyushh's Portfolio"
theme = "imidiotic"

[params]
# Meta data
description = "The portfolio website of Piyushh Bhutoria."
author = "Piyushh Bhutoria"

[menus]
  [[menus.main]]
  name = "LinkedIn"
  URL = "https://www.linkedin.com/in/piyushh-bhutoria"
  weight = 1

  [[menus.main]]
  name = "GitHub"
  URL = "https://github.com/Piyushhbhutoria"
  weight = 2

  [[menus.main]]
  name = "Medium"
  URL = "https://medium.com/@piyushhbhutoria"
  weight = 3

  [[menus.main]]
  name = "Peerlist"
  URL = "https://peerlist.io/piyushh"
  weight = 4

  [[menus.main]]
  name = "X"
  URL = "https://x.com/PiyushhB"
  weight = 5

  [[menus.main]]
  name = "Projects"
  URL = "#projects"
  weight = 6

  [[menus.main]]
  name = "Who am I?"
  URL = "index.html"
  weight = 7
